version: "3"

services:
  tomochain:
    build: ./tomochain
    image: tomo/tomochain
    volumes:
      - "tomochain:/build/tomochain"
      - "./tomochain/.pwd:/build/.pwd"
    restart: "on-failure:10"
    ports:
      - "30303:30303"
    networks:
      - back-net
      - monitor-net

  tmcplorer:
    build: ./monitor/tmcplorer
    restart: "on-failure:10"
    depends_on:
      - mongodb
      - tomochain
    ports:
      - "3001:80"
    networks:
      - front-net
      - monitor-net

  app:
    build: ./
    image: tomo/app
    restart: "on-failure:10"
    depends_on:
      - tomochain
    networks:
      - front-net
      - monitor-net

  mongodb:
    image: mongo:3.4
    volumes:
      - "mongodb:/data/db"
    networks:
      - back-net
      - monitor-net

volumes:
  mongodb:
  tomochain:

networks:
  front-net:
  back-net:
  monitor-net:
