version: "3"

services:
  nginx:
    build: ./nginx
    restart: "on-failure:10"
    volumes:
      - ./nginx/app.template:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.template:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-net

  tomochain:
    build: ./tomochain
    image: tomo/tomochain
    volumes:
      - "tomochain:/build/tomochain"
      - "./tomochain/.pwd:/build/.pwd"
    restart: "on-failure:10"
    ports:
      - "30303:30303"
    networks:
      - back-net

  app:
    build: ./
    image: tomo/app
    restart: "on-failure:10"
    depends_on:
      - tomochain
    env_file: .env
    networks:
      - front-net
      - back-net

  mongodb:
    image: mongo:3.4
    volumes:
      - "mongodb:/data/db"
    networks:
      - back-net

volumes:
  mongodb:
  tomochain:

networks:
  front-net:
  back-net:
